routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('sent-email',"EmailController@sentEmail");

Route::resource("students","StudentController");


Route::get('/debug-sentry', function () {
    throw new Exception('hello error!');
});

Route::get('/', function () {
    return view('welcome');
});

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    //

    public function mobileStudent(){
        return $this->hasOneThrough(Student::class, Mobile::class);
    }
}

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //

    public function products()
    {
        return $this->hasManyThrough(Product::class, Company::class);
    }
}

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    //
}

app/Mobile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mobile extends Model
{
    //
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
}

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Student extends Model
{
    use SoftDeletes;
    //
    protected $fillable=['first_name','last_name',"email","gender"];

   function getAllStudent(){

       return Student::all();

   }
    function createStudent($data){

        return Student::create($data);

    }
    function updateStudent($data,$id){

        return Student::where('id',$id)->update($data);

    }
    function deleteStudent($id){

        return Student::find($id)->delete();

    }
    function getStudent($id){

        return Student::find($id);

    }
    function teachers(){
        return $this->belongsToMany(Teacher::class,'student_teacher','student_id','teacher_id');

    }
}

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    //

    public function students(){
        return $this->belongsToMany(Student::class,'student_teacher','teacher_id','student_id');
    }


}

app/Team.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmailController.php
<?php

namespace App\Http\Controllers;

use App\Mail\TestEmail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class EmailController extends Controller
{
    //

    public function sentEmail(){



        $data = ['message' => 'This is a test!'];

        Mail::to('jabbaralisoomro1@gmail.com')->send(new TestEmail($data));
        }
}

app/Http/Controllers/StudentController.php
<?php
#authur Jabbar

namespace App\Http\Controllers;

use App\Brand;
use App\Http\Requests\studentRequest;
use App\Jobs\WelcomeJob;
use App\Mail\WelcomeMail;
use App\Student;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;

class StudentController extends Controller
{

    private $student;

    public function __construct()
    {

        $this->student = new Student();

    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //

//            many to many
//        dd(Student::with('teachers')->get());

        // through one
//        dd(Brand::with('mobileStudent')->get());
        $students = $this->student->getAllStudent();


        return view("student.index", compact("students"));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //

        return view("student.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(studentRequest $request)
    {
        DB::beginTransaction();
        try {
            $data = $request->only('first_name', 'last_name', 'gender', 'email');
            $user=$this->student->createStudent($data);
            WelcomeJob::dispatch($user)->delay(now()->addMinutes(1));
        } catch (Exception $e) {
            DB::rollBack();
            Log::debug($e);
        } finally {
            DB::commit();
        }


//        dd("working");

        return redirect()->route('students.index')->with(["sucess" => __("error.record.created")]);
        //
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        //
        $student = $this->student->getStudent($id);
        return view("student.edit", compact('student'));
    }

    /**
     * @Authur :Jabbar Ali Soomro
     * @Dated
     */

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(studentRequest $request, $id)
    {
        //
        DB::beginTransaction();

        try {
            $data = $request->only('first_name', 'last_name', 'gender', 'email');
            $this->student->updateStudent($data, $id);
        } catch (Exception $e) {
            DB::rollBack();
            Log::debug($e);
        } finally {
            DB::commit();
        }


        return redirect()->route('students.index')->with(["sucess" => __("error.record.updated")]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        DB::beginTransaction();
        try {

            $this->student->deleteStudent($id);
        } catch (Exception $e) {
            DB::rollBack();
            Log::debug($e);
        } finally {
            DB::commit();
        }

        return redirect()->route('students.index')->with(["sucess" => __("error.record.deleted")]);
        //
    }
}

resources/views/student/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>


<div class="container">
    <h1>Create Student</h1>
    <form action="{{route("students.store")}}" method="post">
        {{csrf_field()}}

            <div class="form-group">
            <label for="exampleInputEmail1">First Name</label>
            <input type="text" name="first_name" value="{{old('first_name')}}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Last Name">

                @if($errors->has('first_name'))
                    <small id="emailHelp" class="form-text text-muted">{{ $errors->first('first_name') }}</small>

                @endif

        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Last Name</label>
            <input type="text"  name="last_name" class="form-control" id="exampleInputEmail1"  value="{{old('last_name')}}" aria-describedby="emailHelp" placeholder="Enter Last Name">

            @if($errors->has('last_name'))
                <small id="emailHelp" class="form-text text-muted">{{ $errors->first('last_name') }}</small>

            @endif

        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Email</label>
            <input type="email" name="email" class="form-control"  value="{{old('email')}}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Email Name">
            @if($errors->has('email'))
                <small id="emailHelp" class="form-text text-muted">{{ $errors->first('email') }}</small>
            @endif
        </div>
        <div class="form-group">
            <label for="exampleFormControlSelect1">Gender</label>

            <select name="gender" class="form-control" id="exampleFormControlSelect1">
                @foreach(config('contact.gender') as $gender )
                <option  @if($gender==old('gender')) selected  @endif  value="{{$gender}}">{{$gender}}</option>
                @endforeach

            </select>
            @if($errors->has('gender'))
                <small id="emailHelp" class="form-text text-muted">{{ $errors->first('gender') }}</small>

            @endif

        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

</body>
</html>

resources/views/student/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>


<div class="container">
    <h1>Edit Student</h1>
    <form action="{{route("students.update",$student->id)}}" method="post">
        @method("put")
        {{csrf_field()}}

        <div class="form-group">
            <label for="exampleInputEmail1">First Name</label>
            <input type="text" name="first_name" value="{{old('first_name',$student->first_name)}}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Last Name">

            @if($errors->has('first_name'))
                <small id="emailHelp" class="form-text text-muted">{{ $errors->first('first_name') }}</small>

            @endif

        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Last Name</label>
            <input type="text"  name="last_name" class="form-control" id="exampleInputEmail1"  value="{{old('last_name',$student->last_name)}}" aria-describedby="emailHelp" placeholder="Enter Last Name">

            @if($errors->has('last_name'))
                <small id="emailHelp" class="form-text text-muted">{{ $errors->first('last_name') }}</small>

            @endif

        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Email</label>
            <input type="email" name="email" class="form-control"  value="{{old('email',$student->email)}}" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Email Name">
            @if($errors->has('email'))
                <small id="emailHelp" class="form-text text-muted">{{ $errors->first('email') }}</small>
            @endif
        </div>
        <div class="form-group">
            <label for="exampleFormControlSelect1">Gender</label>

            <select name="gender" class="form-control" id="exampleFormControlSelect1">
                @foreach(config('contact.gender') as $gender )
                    <option  @if($gender==old('gender',$student->gender)) selected  @endif  value="{{$gender}}">{{$gender}}</option>
                @endforeach

            </select>
            @if($errors->has('gender'))
                <small id="emailHelp" class="form-text text-muted">{{ $errors->first('gender') }}</small>

            @endif
            <input type="hidden" name="id" value="{{$student->id}}">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

</body>
</html>

resources/views/student/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>


<div class="container">
    <h2>Student <a href="{{route("students.create")}}" style="float:right"  >create</a></h2>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Email</th>
            <th>Gender</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($students as $student)
            <tr>
                <td>{{$student->first_name}}</td>
                <td>{{$student->last_name}}</td>
                <td>{{$student->email}}</td>
                <td>{{$student->gender}}</td>
                <th>
                    <form action="{{route('students.destroy',$student->id)}}"  onsubmit="return window.confirm('are you sure you want to delete')" method="post">
                        @method("delete")
                       {{csrf_field()}}
                        <input type="submit" value="delete">
                    </form>
                    <a href="{{route('students.edit',$student->id)}}">Edit</a>
                </th>
            </tr>
        @endforeach
        </tbody>
    </table>

    @if(\Session::get('sucess'))
    <div>{{\Session::get('sucess')}}</div>
    @endif
</div>

</body>
</html>